Portfolio/ASP.NET MVC/TryMVC/TryMVC/Models/ProductModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TryMVC.Models
{
    public class ProductModels
    {
        public string pId { get; set; }
        public string pName { get; set; }
        public decimal Price { get; set; }

        public static ProductModels GetDefault()
        {
            return new ProductModels()
            {
                pId = string.Empty,
                pName = string.Empty,
                Price = 10,
            };
        }
    }
}

Portfolio/ASP.NET MVC/TryMVC/TryMVC/Models/UserInfoModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TryMVC.WebSite.Services;

namespace TryMVC.Models
{
    public class UserInfoModels
    {
        public Guid UserID { get; set; }
        public string Account { get; set; }
        public string Name { get; set; }
        public string pwd { get; set; }
        public string Email { get; set; }
        public string Birthday { get; set; }

        #region 管理
        /// <summary> 是否啟用 </summary>
        public bool IsEnable { get; set; }
        /// <summary> 建立者帳號代碼 </summary>
        public Guid CreateUser { get; set; }
        /// <summary> 建立時間 </summary>
        public DateTime CreateDate { get; set; }
        /// <summary> 修改者帳號代碼 </summary>
        public Guid? ModifyUser { get; set; }
        /// <summary> 修改時間 </summary>
        public DateTime? ModifyDate { get; set; }
        /// <summary> 刪除者帳號代碼 </summary>
        public Guid? DeleteUser { get; set; }
        /// <summary> 刪除時間 </summary>
        public DateTime? DeleteDate { get; set; }
        #endregion

        public static UserInfoModels GetDefault()
        {
            return new UserInfoModels()
            {
                Account = string.Empty,
                Name = string.Empty,
                pwd = string.Empty,
                Email = string.Empty,
                Birthday = DateTime.Now.ToShortDateString()
            };
        }

        public static UserInfoModels GetModifyDefault(string account)
        {
            UserInfoModels model = SampleDataService.GetUserInfo(account);

            return model;
        }
    }
}

Portfolio/ASP.NET MVC/TryMVC/TryMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TryMVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Portfolio/ASP.NET MVC/TryMVC/TryMVC/Controllers/UserServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TryMVC.Models;
using TryMVC.WebSite.Services;

namespace TryMVC.Controllers
{
    public class UserServiceController : Controller
    {
        // GET: UserService
        public ActionResult Index()
        {
            var list = SampleDataService.GetUserList();
            return View(list);
        }

        // GET: UserService/Create
        public ActionResult Create()
        {
            var obj = UserInfoModels.GetDefault();
            return View("Create", obj);
        }
 
        // Post: UserService/Create
        [HttpPost]
        public ActionResult Create(UserInfoModels model)
        {
            var newmodel = new UserInfoModels();
            newmodel.Account = model.Account;
            newmodel.Name = model.Name;
            newmodel.pwd = model.pwd;
            newmodel.Email = model.Email;
            newmodel.Birthday = model.Birthday;
            SampleDataService.CreateUser(newmodel);

            return RedirectToAction("Index");
        }

        // GET: UserService/Edit
        public ActionResult Edit(UserInfoModels model)
        {
            var viewModel = SampleDataService.GetUserInfo(model.Account);
            return View("Edit", viewModel);
        }

        // Post: UserService/Edit
        [HttpPost]
        public ActionResult Edit(UserInfoModels model, string account)
        {
            var orgModel = SampleDataService.GetUserInfo(model.Account);

            var newmodel = new UserInfoModels();
            newmodel.Account = orgModel.Account;
            newmodel.Name = model.Name;
            newmodel.pwd = model.pwd;
            newmodel.Email = model.Email;
            newmodel.Birthday = orgModel.Birthday;
            SampleDataService.ModifyUserInfo(newmodel);

            return RedirectToAction("Index");
        }

        // Post: UserService/Delete
        [HttpPost]
        public ActionResult Delete(UserInfoModels model)
        {
            SampleDataService.DeleteUser(model.Account);

            return RedirectToAction("Index");
        }
    }
}

Portfolio/ASP.NET MVC/TryMVC/TryMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>ホームページ</h2>

<a href="@Url.Action("Index", "UserService", new { ID = string.Empty })" class="btn btn-primary font-weight-bolder">人員管理システム</a>

Portfolio/ASP.NET MVC/TryMVC/TryMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title 管理システム</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("管理システム", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year 管理会社</p>
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Portfolio/ASP.NET MVC/TryMVC/TryMVC/Views/UserService/Create.cshtml
@using TryMVC.Models
@model UserInfoModels
@{
    ViewBag.Title = "Create";

    string ctlName = "UserService";

    string postActionName = "Create";



}



<div class="row">
    <div class="col-xl-12">
        <div class="card card-custom">
            <!--begin::Card header-->
            <div class="card-header">
                <div class="card-title">
                    <h3 class="card-label">
                        @(this.Model.Account)
                    </h3>
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm(postActionName, ctlName, FormMethod.Post, new { @class = "form" }))
                {
                    <div class="tab-content">
                        <!--begin::Tab-->
                        <div class="tab-pane show px-7 active" id="kt_user_edit_tab_1" role="tabpanel">
                            <!--begin::Row-->
                            <div class="row">
                                <div class="col-xl-2"></div>
                                <div class="col-xl-7 my-2">
                                    <!--begin::Row-->
                                    <div class="row">
                                        <label class="col-3"></label>
                                        <div class="col-9">
                                            <h6 class="text-dark font-weight-bold mb-10">個人資訊</h6>
                                        </div>
                                    </div>
                                    <!--end::Row-->
                                    <!--begin::Group-->
                                    <div class="form-group row">
                                        <label class="col-form-label col-3 text-lg-right text-left">@Html.DisplayNameFor(model => model.Account)</label>
                                        <div class="col-9">
                                            <input class="form-control form-control-lg form-control-solid" type="text" name="account" value="@Html.DisplayFor(model => model.Account)" placeholder="please input Account">
                                        </div>
                                    </div>
                                        <!--end::Row-->
                                        <!--begin::Group-->
                                    <div class="form-group row">
                                        <label class="col-form-label col-3 text-lg-right text-left">@Html.DisplayNameFor(model => model.pwd)</label>
                                        <div class="col-9">
                                            <input class="form-control form-control-lg form-control-solid" type="text" name="pwd" value="@Html.DisplayFor(model => model.pwd)" placeholder="please input password">
                                        </div>
                                    </div>
                                            <!--end::Group-->
                                            <!--begin::Group-->
                                            <div class="form-group row">
                                                <label class="col-form-label col-3 text-lg-right text-left">@Html.DisplayNameFor(model => model.Name)</label>
                                                <div class="col-9">
                                                    <input class="form-control form-control-lg form-control-solid" type="text" name="Name" value="@Html.DisplayFor(model => model.Name)" placeholder="please input name">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-form-label col-3 text-lg-right text-left">@Html.DisplayNameFor(model => model.Email)</label>
                                                <div class="col-9">
                                                    <input class="form-control form-control-lg form-control-solid" type="email" name="Email" value="@Html.DisplayFor(model => model.Email)" placeholder="please input Email">
                                                </div>
                                            </div>
                                            <!--end::Group-->
                                            <!--begin::Group-->
                                            <div class="form-group row">
                                                <label class="col-form-label col-3 text-lg-right text-left">@Html.DisplayNameFor(model => model.Birthday)</label>
                                                <div class="col-9">
                                                    <input class="form-control form-control-lg form-control-solid" type="date" name="BTD" value="@Html.DisplayFor(model => model.Birthday)"  placeholder="please select Birthday">
                                                </div>
                                            </div>
                                            <!--end::Group-->
                                        </div>
                            </div>
                            <!--end::Row-->
                        </div>
                        <!--end::Tab-->
                    </div>

                    <div class="d-flex justify-content-between border-top pt-10">
                        <div class="mr-2">
                            <a href="@Url.Action("Index", "UserService")" class="btn btn-light font-weight-bolder text-uppercase px-9 py-4">
                                返回
                            </a>
                        </div>
                        <div>
                            <button type="submit" onclick="return confirm('確定新增使用者?')" class="btn btn-success font-weight-bolder text-uppercase px-9 py-4" data-wizard-type="action-submit">送出</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
                
</div>

Portfolio/ASP.NET MVC/TryMVC/TryMVC/Views/UserService/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

Portfolio/ASP.NET MVC/TryMVC/TryMVC/Views/UserService/Edit.cshtml
@using TryMVC.Models
@model UserInfoModels
@{
    ViewBag.Title = "Edit";

    string ctlName = "UserService";

    string postActionName = "Edit";

}

<div class="row">
    <div class="col-xl-12">
        <div class="card card-custom">
            <!--begin::Card header-->
            <div class="card-header">
                <div class="card-title">
                    <h3 class="card-label">
                        @(this.Model.Account)
                    </h3>
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm(postActionName, ctlName, FormMethod.Post, new { @class = "form" }))
                {
                    <div class="tab-content">
                        <!--begin::Tab-->
                        <div class="tab-pane show px-7 active" id="kt_user_edit_tab_1" role="tabpanel">
                            <!--begin::Row-->
                            <div class="row">
                                <div class="col-xl-2"></div>
                                <div class="col-xl-7 my-2">
                                    <!--begin::Row-->
                                    <div class="row">
                                        <label class="col-3"></label>
                                        <div class="col-9">
                                            <h6 class="text-dark font-weight-bold mb-10">個人資訊</h6>
                                        </div>
                                    </div>
                                    <!--end::Row-->
                                    <!--begin::Group-->
                                    <div class="form-group row">
                                        <label class="col-form-label col-3 text-lg-right text-left">@Html.DisplayNameFor(model => model.Account)</label>
                                        <div class="col-9">
                                            <input class="form-control form-control-lg form-control-solid" type="text" name="account" value="@Html.DisplayFor(model => model.Account)" readonly>
                                        </div>
                                    </div>
                                </div>
                                <!--end::Row-->
                                <!--begin::Group-->
                                <div class="form-group row">
                                    <label class="col-form-label col-3 text-lg-right text-left">@Html.DisplayNameFor(model => model.pwd)</label>
                                    <div class="col-9">
                                        <input class="form-control form-control-lg form-control-solid" type="text" name="pwd" value="@Html.DisplayFor(model => model.pwd)" placeholder="please input password">
                                    </div>
                                </div>
                                <!--end::Group-->
                                <!--begin::Group-->
                                <div class="form-group row">
                                    <label class="col-form-label col-3 text-lg-right text-left">@Html.DisplayNameFor(model => model.Name)</label>
                                    <div class="col-9">
                                        <input class="form-control form-control-lg form-control-solid" type="text" name="Name" value="@Html.DisplayFor(model => model.Name)" placeholder="please input name">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-form-label col-3 text-lg-right text-left">@Html.DisplayNameFor(model => model.Email)</label>
                                    <div class="col-9">
                                        <input class="form-control form-control-lg form-control-solid" type="email" name="Email" value="@Html.DisplayFor(model => model.Email)" placeholder="please input Email">
                                    </div>
                                </div>
                                <!--end::Group-->
                                <!--begin::Group-->
                                <!--<div class="form-group row">
                                <label class="col-form-label col-3 text-lg-right text-left">@Html.DisplayNameFor(model => model.Birthday)</label>
                                <div class="col-9">
                                    <input class="form-control form-control-lg form-control-solid" type="date" name="BTD" value="@Html.DisplayFor(model => model.Birthday)" placeholder="please select Birthday">
                                </div></div>-->
                                <!--end::Group-->
                            </div>
                        </div>
                        <!--end::Row-->
                    </div>
                    <!--end::Tab-->

                    <div class="d-flex justify-content-between border-top pt-10">
                        <div class="mr-2">
                            <a href="@Url.Action("Index", "UserService")" class="btn btn-light font-weight-bolder text-uppercase px-9 py-4">
                                返回
                            </a>
                        </div>
                        <div>
                            <button type="submit" onclick="return confirm('資料即將修改，繼續請確定')" class="btn btn-success font-weight-bolder text-uppercase px-9 py-4" data-wizard-type="action-submit">送出</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Portfolio/ASP.NET MVC/TryMVC/TryMVC/Views/UserService/Index.cshtml
@model IEnumerable<TryMVC.Models.UserInfoModels>

@{
    ViewBag.Title = "人員管理システム";
    string ctlName = "UserService";
}

<div class="row">
    <div class="col-xl-12">
        <!--begin::Card-->
        <div class="card card-custom gutter-b">
            <div class="card-header">
                <div class="card-title">
                    <h3 class="card-label">
                        @ViewBag.Title
                    </h3>
                </div>
            </div>
            <div class="card-body">
                <p>
                    <a href="@Url.Action("Create")" class="btn btn-primary">
                        <i class="flaticon2-plus"></i> 追加
                    </a>
                </p>
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col" class="col-sm-3">@Html.DisplayNameFor(model => model.Account)</th>
                            <th scope="col" class="col-sm-2">@Html.DisplayNameFor(model => model.Name)</th>
                            <th scope="col" class="col-sm-2">@Html.DisplayNameFor(model => model.Email)</th>
                            <th scope="col" class="col-sm-2">@Html.DisplayNameFor(model => model.Birthday)</th>
                            <th scope="col" class="col-sm-3">Act</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td scope="row">
                                    @Html.DisplayFor(modelItem => item.Account)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Birthday)
                                </td>
                                <td>
                                    <div class="d-flex flex-row">
                                        <a href="@Url.Action("Edit", new { account = item.Account })" class="btn btn-warning">
                                            <i class="flaticon2-pen"></i> 編集
                                        </a>
                                        &nbsp;
                                        @using (@Html.BeginForm("Delete", ctlName, FormMethod.Post, new { @class = "form-column" }))
                                        {
                                    <button type="submit" class="btn btn-danger" name="BtnType" value="Delete" onclick="return confirm('您確定要刪除嗎?')">
                                        <i class="flaticon2-delete"></i> 削除
                                        @Html.Hidden("account", item.Account)
                                    </button>
                                        }
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!--end::Card-->
    </div>
</div>